### PR TITLE
Collapse filters

### LINKED ISSUE #156: Make B checkboxes collapsible
collapse up into "Filter Benefits" title.

https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5ace60ce8d600d225c0e1b34

image

### PR DESCRIPTION
**Pull request by sastels**
resolves #156 

collapse benefit / patron types filters in B up into filter title

### CODE REVIEW

**Comment by maxneuvians** [comment]
Looking really nice!

**Comment by maxneuvians** [comment]
What do you think about switching these the title and selector in B and have the title field (At this time there are no benefits that match your selections.) below the filters. Also maybe have the filters show a summary when collapsed? "3 selected". Also have filters closed when on mobile?

screen shot 2018-05-07 at 10 31 27 am

**Review by maxneuvians — APPROVED** [review]
Looks great! 🦑

**Comment by sastels** [comment]
Going to leave the summary line for later. Changed the "there are no benefits" message to "Select a status" or "Select a need" if the corresponding filters have no selections.

**Comment by maxneuvians** [comment]
👍

**Pull request merged**
