### PR TITLE
Update banner logo

### LINKED ISSUE #781: Switch to VAC banner
screen shot 2018-08-02 at 2 56 32 pm

### PR DESCRIPTION
**Pull request by smcmurtry**
Closes #781

### CODE REVIEW

**Comment by sastels** [comment]
Can we get it to shrink a bit like the old one did?

image

**Comment by maxneuvians** [comment]
Need to close and open to kick the heroku PR app

**Comment by maxneuvians** [comment]
Can we delete these files?
```
../static/vac-sig-eng-2018.svg
../static/vac-sig-eng-2018-white.svg
../static/vac-sig-fra-2018-white.svg
```

Otherwise looks great!

**Comment by smcmurtry** [comment]
Awesome work getting that `FIP` component to work!

**Review by thomascraig — APPROVED** [review]

**Pull request merged**
