### PR TITLE
Option B embedded cards

### LINKED ISSUE #571: option B embedded benefit card
make option B version of these cards.

image

### PR DESCRIPTION
**Pull request by sastels**
resolves #571 

make embedded cards the new look.

Note that since Option B doesn't currently show the embedded cards I've added them temporarily to Option A. I'll switch Option A to use the original cards before merging this PR.

### CODE REVIEW

**Comment by maxneuvians** [comment]
screen shot 2018-07-16 at 3 34 33 pm

Two suggestions:
- Align the title left, we are doing that somewhere else (bookmarks button I think)
- Look into the CSS `line-height` to give it some more space https://www.w3schools.com/cssref/tryit.asp?filename=trycss_line-height

**Comment by maxneuvians** [comment]
Nice work on the UI!

**Comment by smcmurtry** [comment]
Looks good! I think you need a bit more white space between the text and the card border to make it look like the designs.

**Review by smcmurtry — APPROVED** [review]
Looks good! 🦑

**Pull request merged**
