### PR TITLE
Removed MUI from print page

### LINKED ISSUE #1527: Print page fonts
The print page first pops up in one font, and then changes font if the user clicks the cancel button on the print popup window. 

screen shot 2018-12-04 at 8 45 50 am
screen shot 2018-12-04 at 8 45 59 am

### LINKED ISSUE #1537: Remove MUI theme from print page
It's not being used here anymore.

### PR DESCRIPTION
**Pull request by SupeDeDupe**
Closes #1537

### CODE REVIEW

**Comment by brdunfield** [comment]
I still see the bug on this build

**Comment by SupeDeDupe** [comment]
Weird stuff. If you open the print page in a different tab, the bug appears nonexistent.

**Comment by SupeDeDupe** [comment]
Changed the issue this closes so it can be merged.

**Review by smcmurtry — APPROVED** [review]
🦑

**Pull request merged**
