### PR TITLE
[WIP] Add green border to Paper component

### LINKED ISSUE #1826: Add green bar to the top of page cards
See: https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5b45ad8f38da59ab5e754fe3
And: https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5b758b93c7fdc4922413a6fb

### PR DESCRIPTION
**Pull request by brdunfield**
Closes #1826

### CODE REVIEW

**Comment by smcmurtry** [comment]
I think the breadcrumbs should be aligned with the card: 
screen shot 2019-02-13 at 12 08 43 pm

vs

screen shot 2019-02-13 at 12 10 10 pm

**Comment by brdunfield** [comment]
How much layout changes should be added into this PR? There's a lot of work to do on the GE layout that I was going to put in a separate PR, but on some thought I've already put some of it into this one - it's not purely just the green bar.. Thoughts?

**Comment by smcmurtry** [comment]
Also we lost the space between the stuff in the headers and the left and right edges of the screen on mobile: 
screen shot 2019-02-13 at 12 13 15 pm

Same goes for the footers.

**Review by smcmurtry — APPROVED** [review]
Nice work! 🦑 🦑

**Pull request merged**
