### PR TITLE
Favourites Info Column added white bg color

### LINKED ISSUE #1119: Put right-hand side content on favourites page in a card
https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5b562e457ff49a75561f23b8

screen shot 2018-09-04 at 3 12 18 pm

### PR DESCRIPTION
**Pull request by apmcguigan**
closes #1119

### CODE REVIEW

**Comment by smcmurtry** [comment]
@apmcguigan Looks like it's supposed to have 25px of padding not 12px, and it has a slight border/shadow around the edges. Maybe try making in a paper or card component? I think that will add the shadow automatically.

**Comment by apmcguigan** [comment]
Heading home for the day, feel free to merge if approved

**Review by sastels — APPROVED** [review]
Looks sharp! 🦑

**Comment by smcmurtry** [comment]
Looks good to me too! We may want to have a margin between the card edge and the screen edge on small screens like on the other pages. But that could be a separate PR.

**Pull request merged**
