### PR TITLE
Mobile share_modal styling

### PR DESCRIPTION
**Pull request by brdunfield**
I made the extreme small view have a full size input / button, and adjusted the widths in various other views so that it looked good to me. Let me know what you think.

### CODE REVIEW

**Review by SupeDeDupe — APPROVED** [review]
Looks good! :ghost:

**Comment by smcmurtry** [comment]
Looks good! Only change I would suggest is some white space between the copy button and the text box:
screen shot 2018-11-27 at 10 04 03 am

**Comment by brdunfield** [comment]
screen shot 2018-11-27 at 3 49 41 pm

@smcmurtry how's this?

**Comment by smcmurtry** [comment]
great work!

**Pull request merged**
