### PR TITLE
Filter radio buttons

### LINKED ISSUE #252: Change filters to radio buttons and change questions/options
https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5b1156c59194e27a365f8a25?did=5b11610f5696c3a573bdfa04&cmid=5b11610f5696c3a573bdfa05

### PR DESCRIPTION
**Pull request by smcmurtry**
Resolves #252 

Changed the filter buttons from dropdown to radio.
Changed the data model for the selected eligibility criteria from `selection = {x: "x"}` to `selection = "x"` since we aren't doing a multi select any more.

### CODE REVIEW

**Comment by sastels** [comment]
Odd, why are there asterisks after the legends?
8a1e24d5-2344-431d-a967-f62f985484d7

**Comment by smcmurtry** [comment]
It's default behaviour for `<FormLabel>`. I'll try to change it.

**Comment by smcmurtry** [comment]
I was wrong - not default behaviour. I accidentally included a required attribute.

**Review by sastels — APPROVED** [review]
:shipit:

**Comment by smcmurtry** [comment]
closes #252

**Pull request merged**
