### PR TITLE
Security update

### PR DESCRIPTION
**Pull request by brdunfield**
#1381

### CODE REVIEW

**Comment by sastels** [comment]
I think that the `react-i18next` major upgrade is still breaking the app, as mentioned in https://github.com/cds-snc/vac-benefits-directory/issues/1223. We should probably fix this :/

**Comment by brdunfield** [comment]
Do you want me to revert just the breaking dependency on this PR so the other security updates go through? And move #1223 to the current sprint?

**Comment by brdunfield** [comment]
Should be working now!

**Review by sastels — APPROVED** [review]
Looks good! 🦑

**Pull request merged**
