### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by maxneuvians**
Fixes for #302 and #301

### CODE REVIEW

**Comment by smcmurtry** [comment]
the deployment url is showing "Application Error"

**Comment by maxneuvians** [comment]
Just asked @sastels to take a look at the heroku logs

**Comment by sastels** [comment]
restarted dynos and tested app, seems fine now.

**Review by sastels — APPROVED** [review]
no idea why the app crashed. seems fine now.

**Comment by maxneuvians** [comment]
👺 in the machine

**Pull request merged**
