### PR TITLE
Ben dir mobile new design

### LINKED ISSUE #1917: Update mobile card design
see: https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5c5c6c0921ae342cd28bcdf2

### PR DESCRIPTION
**Pull request by SupeDeDupe**
Closes #1917 
Made a bunch of smaller changes to closer match design:
- fixed padding on breadcrumbs
- changed the width of the paper appearing on the GE and ben dir
- changed some font colours in the quick links, sticky header, share box, and grey box all in ben dir
- decreased mobile font size in sticky header
- made the mobile content text consistent with the text being used in the design

### CODE REVIEW

**Comment by brdunfield** [comment]
Does this branch have the GE styling from Master merged into it?

Looks like the Learn More and Save to your List buttons are supposed to be full width and centered, but they are left aligned in this PR.

**Comment by brdunfield** [comment]
Oh I didn't see #1953 😬

**Comment by SupeDeDupe** [comment]
@brdunfield Yep, was about to point that one out. I felt this issue probably should have been divided into smaller issues.

**Comment by brdunfield** [comment]
This still has wonky button layouts in the GE on smaller screen sizes compared to master.
screen shot 2019-03-06 at 9 09 17 am
screen shot 2019-03-06 at 9 09 55 am

In the interest of keeping master in a good state we might want to roll #1953 into this PR?

**Comment by smcmurtry** [comment]
@brdunfield are you sure you're looking at the latest version of master? it looks to me like master also has this behaviour.

**Comment by brdunfield** [comment]
Weird, when I checked earlier today I made sure to refresh and it looked better, but a fresh check now also shows this behaviour, you're right. 🤔

**Review by smcmurtry — APPROVED** [review]
looks good! 🦑

**Pull request merged**
