### PR TITLE
Security update T+4

### PR DESCRIPTION
**Pull request by brdunfield**
#1426

### CODE REVIEW

**Comment by sastels** [comment]
Heroku is unhappy with this
```
2018-11-21T19:51:50.154799+00:00 app[web.1]: yarn run v1.12.3

2018-11-21T19:51:50.328969+00:00 app[web.1]: $ NODE_ENV=production node server.js

2018-11-21T19:51:51.408717+00:00 app[web.1]: (node:31) UnhandledPromiseRejectionWarning: TypeError: method is not a function

2018-11-21T19:51:51.408740+00:00 app[web.1]:     at paginate (/app/utils/statistics.js:17:26)

2018-11-21T19:51:51.408742+00:00 app[web.1]:     at getGithubData (/app/utils/statistics.js:28:24)

2018-11-21T19:51:51.408744+00:00 app[web.1]:     at getAllData (/app/server.js:24:28)

2018-11-21T19:51:51.408745+00:00 app[web.1]:     at Object.<anonymous> (/app/server.js:38:17)

2018-11-21T19:51:51.408748+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:722:30)

2018-11-21T19:51:51.408749+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)

2018-11-21T19:51:51.408751+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:620:32)

2018-11-21T19:51:51.408753+00:00 app[web.1]:     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)

2018-11-21T19:51:51.408755+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:552:3)

2018-11-21T19:51:51.408756+00:00 app[web.1]:     at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)

2018-11-21T19:51:51.410086+00:00 app[web.1]: (node:31) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

2018-11-21T19:51:51.410281+00:00 app[web.1]: (node:31) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by brdunfield** [comment]
Looks like the octokit/rest upgrade. Will investigate when time permits.

**Comment by brdunfield** [comment]
@sastels Fixed!

**Review by smcmurtry — APPROVED** [review]
LGTM! 🦑

**Pull request merged**
