### PR TITLE
search box highlight fixed

### LINKED ISSUE #1763: Search box turns yellow when keyword is inputted
When I searched a word, the text box background turned yellow.

### PR DESCRIPTION
**Pull request by apmcguigan**
closes #1763

### CODE REVIEW

**Comment by apmcguigan** [comment]
Pushing this up as an alternative, overall it looks better but breaks the outline when the search bar is selected. Likely due to the ClearButton covering the outline

search-45px

**Comment by smcmurtry** [comment]
Hmm, not sure this is an improvement. What about removing the yellow background entirely and keeping the focus border? https://stackoverflow.com/questions/2781549/removing-input-background-colour-for-chrome-autocomplete

**Comment by apmcguigan** [comment]
Heroku deployment doesnt seem to be working, currently looks like this on my end in Chrome
search-good

**Review by SupeDeDupe — APPROVED** [review]
Nice! 🦑👍

**Pull request merged**
