### PR TITLE
PR average duration graph

### LINKED ISSUE #681: Stats page: show average code review time (time PR existed before merge)
This should be around a day

### PR DESCRIPTION
**Pull request by sastels**
resolves #681

### CODE REVIEW

**Comment by maxneuvians** [comment]
Really cool chart - nice work. The JS is broken though, in the console you get Highcharts error #15: www.highcharts.com/errors/15

**Comment by maxneuvians** [comment]
No test 😢

**Comment by sastels** [comment]
LOL I haven't requested reviews yet!

Also: Highcharts also throws that error on master / Azure. Let me check git blame... :)

**Comment by maxneuvians** [comment]
Ooops - did not see that, was too excited

**Comment by sastels** [comment]
tsk tsk, the releases weren't sorted, that was throwing the error.

**Review by maxneuvians — APPROVED** [review]
🦑 Really nice work!

**Pull request merged**
