### PR TITLE
Made the card header more like the design

### PR DESCRIPTION
**Pull request by smcmurtry**
A part of #1107 (but it's not closed yet)

### CODE REVIEW

**Comment by smcmurtry** [comment]
I'm going to try adding the new icon file

**Comment by smcmurtry** [comment]
@michellengaiCDS I've worked for a couple hours to get the new svg icon to scale to our desired size, but I haven't been able to scale it a predictable way. Maybe we can revisit this later.

**Review by sastels — APPROVED** [review]
Looks good! 🦑

**Comment by michellengaiCDS** [comment]
it looks so good!

**Pull request merged**
