### PR TITLE
Make breakpoints consistent with VAC site

### LINKED ISSUE #1944: Make breakpoints in the app more consistent with the VAC site
Currently we're using the default breakpoints that come with the material ui `Grid` component. Is this something we can change? Currently our breakpoints don't match up with the VAC site, which means our layout doesn't match theirs at certain screen widths.

### PR DESCRIPTION
**Pull request by brdunfield**
Closes #1944

### CODE REVIEW

**Comment by brdunfield** [comment]
[Implement UI changes to match new VAC site](https://trello.com/c/WzhdqieD/196-implement-ui-changes-to-match-new-vac-site)

**Comment by brdunfield** [comment]
[Implement UI changes to match new VAC site](https://trello.com/c/WzhdqieD/196-implement-ui-changes-to-match-new-vac-site)

**Comment by brdunfield** [comment]
[Implement UI changes to match new VAC site](https://trello.com/c/WzhdqieD/196-implement-ui-changes-to-match-new-vac-site)

**Comment by brdunfield** [comment]
[Implement UI changes to match new VAC site](https://trello.com/c/WzhdqieD/196-implement-ui-changes-to-match-new-vac-site)

**Comment by brdunfield** [comment]
[Implement UI changes to match new VAC site](https://trello.com/c/WzhdqieD/196-implement-ui-changes-to-match-new-vac-site)

**Comment by brdunfield** [comment]
[Implement UI changes to match new VAC site](https://trello.com/c/WzhdqieD/196-implement-ui-changes-to-match-new-vac-site)

**Comment by brdunfield** [comment]
[Implement UI changes to match new VAC site](https://trello.com/c/WzhdqieD/196-implement-ui-changes-to-match-new-vac-site)

**Comment by brdunfield** [comment]
[Implement UI changes to match new VAC site](https://trello.com/c/WzhdqieD/196-implement-ui-changes-to-match-new-vac-site)

**Comment by brdunfield** [comment]
[Implement UI changes to match new VAC site](https://trello.com/c/WzhdqieD/196-implement-ui-changes-to-match-new-vac-site)

**Comment by brdunfield** [comment]
[Implement UI changes to match new VAC site](https://trello.com/c/WzhdqieD/196-implement-ui-changes-to-match-new-vac-site)

**Comment by brdunfield** [comment]
[Implement UI changes to match new VAC site](https://trello.com/c/WzhdqieD/196-implement-ui-changes-to-match-new-vac-site)

**Comment by brdunfield** [comment]
[Implement UI changes to match new VAC site](https://trello.com/c/WzhdqieD/196-implement-ui-changes-to-match-new-vac-site)

**Comment by brdunfield** [comment]
[Implement UI changes to match new VAC site](https://trello.com/c/WzhdqieD/196-implement-ui-changes-to-match-new-vac-site)

**Comment by brdunfield** [comment]
[Implement UI changes to match new VAC site](https://trello.com/c/WzhdqieD/196-implement-ui-changes-to-match-new-vac-site)

**Comment by smcmurtry** [comment]
For screen widths between 425px and 766px, the padding is missing under the links in the quick links section: 
screen shot 2019-03-04 at 4 04 59 pm

Aside from that this looks great!

**Review by smcmurtry — APPROVED** [review]
Nice work! 🦑

**Pull request merged**
