### PR TITLE
bookmarking of state in url

### LINKED ISSUE #85: Bookmarking : user can return to a certain filter state of the app
With a URL is preferred

### PR DESCRIPTION
**Pull request by sastels**
resolves #85 

Put info in the url when changing sections, and parse it out when the page loads.
```
http://localhost:3000/A?section=A3&selectedBenefitTypes=recQO4AHswOl75poF&selectedPatronTypes=rec726lY5vUBEh2Sv,recDAuNt8DXhD88Mr
```

### CODE REVIEW

**Review by maxneuvians — COMMENTED** [review]
We should test this change with cypress?

**Comment by sastels** [comment]
good Idea. 👍

**Comment by sastels** [comment]
ugh, before we should be using Cypress for E2E testing we need to get Cypress to mock the Airtable calls.

**Comment by maxneuvians** [comment]
Nice LGTM 🦑

**Comment by sastels** [comment]
right now using Cypress to test navigation around the app. Will add Airtable mocking in a different PR.

**Review by maxneuvians — APPROVED** [review]

**Pull request merged**
