### PR TITLE
Changed button style to look closer to a link

### LINKED ISSUE #558: Style Jump buttons in GE
Make them look like links

image

### PR DESCRIPTION
**Pull request by apmcguigan**
Changes card design to match mockup
Closes #558

### CODE REVIEW

**Comment by smcmurtry** [comment]
Looks good! I think we need some commas though.

**Comment by sastels** [comment]
Has trailing commas. Was thinking of this on weekend, best way might be to figure out the list of jump links before the return, then we’d know when we were on the last one.

**Comment by maxneuvians** [comment]
Easiest way in JS to ensure proper comma placement is to make a list and the `.join[', ']`

**Review by sastels — APPROVED** [review]
probably easiest to just merge this in (after fixing the merge conflict) and we can make a new issue to fix up the commas.

**Pull request merged**
