### PR TITLE
Don't render next steps if there are none

### LINKED ISSUE #1755: Next steps header should not be displayed if the list is empty
image

### PR DESCRIPTION
**Pull request by brdunfield**
Closes #1755 . Decided to implement it anyways since it was like a one line fix.

Currently there's no way to test this in the app, since there are 3 next steps in Airtable with no requirements.

I wrote a test for it in jest. If you want to test it in the app, you'll need to modify getBullets() to return an empty array.

### CODE REVIEW

**Comment by SupeDeDupe** [comment]
I just tested it by temporarily editing the records in Airtable. It might be a concern that the next steps link in the sidebar is still there and doesn't redirect to anywhere.

**Comment by brdunfield** [comment]
That's true. It probably shouldn't render in the sidebar if there are no next steps. If it's not too much work I'll update it. But the case of having no next steps probably shouldn't happen so I'm not sure how much work to put into it.

**Comment by smcmurtry** [comment]
I don't think we need to worry about how the app looks if there are no next steps. If there are no next steps, the issue is that they are missing from airtable and should be added. Is there any legitimate case where the user wouldn't be eligible for any next steps? If so that is an edge case that should probably have its own design rather than just hiding things.

**Comment by SupeDeDupe** [comment]
Yeah, at the time when I made the issue originally, I wasn't thinking that the empty list was a bug. Seems like we're getting into a bit of a rabbit hole, so I'd also agree that perhaps we don't need to worry about the case of the list being empty as it would be a content bug....

**Comment by brdunfield** [comment]
So should we just stop this PR here, or is there additional functionality we want in it?

**Comment by smcmurtry** [comment]
My preference is to close without merging.

**Comment by smcmurtry** [comment]
whoops! didn't mean to close it myself :)

**Comment by brdunfield** [comment]
Works for me

**Pull request closed without merging**
