### PR TITLE
Accessibility: Add a "Skip to Main Content" button

### PR DESCRIPTION
**Pull request by brdunfield**

### CODE REVIEW

**Comment by brdunfield** [comment]
[Accessibility: Keyboard Navigation](https://trello.com/c/McZemABK/99-accessibility-keyboard-navigation)

**Comment by smcmurtry** [comment]
I tried testing with voiceover and it does move the page to mainContent, but it doesn't start reading out the main content like on http://www.veterans.gc.ca/eng

I tried changing the mainContent id to be on the `<h1>` element but that didn't seem to help. I'm not sure yet if this bug is related to your PR or just a general issue with `<a>` elements in a react/next app...

**Review by smcmurtry — APPROVED** [review]
Looks good! After more thought I think the voiceover thing is an unrelated issue.

**Comment by brdunfield** [comment]
[Accessibility: Keyboard Navigation](https://trello.com/c/McZemABK/99-accessibility-keyboard-navigation)

**Pull request merged**
