### PR TITLE
K8s manifests

### PR DESCRIPTION
**Pull request by maxneuvians**

### CODE REVIEW

**Review by szinck1 — COMMENTED** [review]
How are getting `AIRTABLE_WRITE_KEY` into the application?

**Comment by maxneuvians** [comment]
Good catch - I will add it in

**Review by szinck1 — COMMENTED** [review]
looks like there's a typo - `vay`

**Comment by maxneuvians** [comment]
Another good catch - should be fixed!

**Review by szinck1 — APPROVED** [review]
LGTM

**Pull request merged**
