### PR TITLE
Data-Val-Needs

### LINKED ISSUE #401: Data Validation: benefits without a need
Add a test that ensures that all benefits have at least one associated need

### PR DESCRIPTION
**Pull request by apmcguigan**
resolves #401

### CODE REVIEW

**Comment by apmcguigan** [comment]
Not sure what happened with the conflicting package.json. Was having some issues getting yarn test to run so had to mess with Node_Modules folder

**Comment by sastels** [comment]
Did you do a fresh `git pull master` before creating the `Data-Val-All-benefits-have-needs` branch?

**Comment by apmcguigan** [comment]
I'm not sure. I think I did one yesterday but then didn't work on the branch until earlier today.

**Comment by apmcguigan** [comment]
Why was test removed from package.json? Is that something that is only needed for setup on my end?

**Comment by maxneuvians** [comment]
I don't think it is something we need.

https://www.npmjs.com/package/test

**Review by maxneuvians — APPROVED** [review]
LGTM 🦑

**Review by sastels — APPROVED** [review]
👍 good job - and it found benefits we don't have needs for! :)

**Pull request merged**
