### PR TITLE
Adding health issue question

### PR DESCRIPTION
**Pull request by smcmurtry**
Working on #370, pair programming with @thomascraig 

Still to do:
-add the health issue response to the url
-add tests

### CODE REVIEW

**Comment by sastels** [comment]
Lol clicking a needs button clears the health question selection 😛

**Comment by smcmurtry** [comment]
@sastels I think this might be because the health issue question isn't being added to the url yet, so when the url is set by making a need selection health issue in redux is erased

**Review by maxneuvians — COMMENTED** [review]
Maybe copy pasta in some tests like this one in `profile_selector_test.js`

https://github.com/cds-snc/vac-benefits-directory/blob/master/__tests__/components/profile_selector_test.js#L83-L102

**Comment by maxneuvians** [comment]
Last suggestion, I promise: 

Add `expect(reduxData.setServiceHealthIssue).toBeCalledWith("");`
after here

https://github.com/cds-snc/vac-benefits-directory/blob/master/__tests__/components/profile_selector_test.js#L158

**Review by maxneuvians — APPROVED** [review]
Awesome work! 🦑

**Pull request merged**
