### PR TITLE
Fixed search bug

### PR DESCRIPTION
**Pull request by maxneuvians**
URL would trim out trailing spaces 🙃 #535

### CODE REVIEW

**Comment by sastels** [comment]
Still seems to be filtering them out

**Comment by maxneuvians** [comment]
screen shot 2018-07-11 at 7 44 00 am

Can you not do this?

**Comment by sastels** [comment]
Yes, but I can do that on the Azure deploy... I thought this was about trailing spaces? I r confuzd.

**Comment by maxneuvians** [comment]
In Chrome when you enter a space it removes it again automagically on Azure deploy currently

**Review by apmcguigan — COMMENTED** [review]
LGTM

**Review by apmcguigan — APPROVED** [review]
LGTM

**Pull request merged**
