### PR TITLE
Sort offices

### LINKED ISSUE #712: Sort offices into provinces if no location is selected
Based on discussion w/ Michelle: to keep it simple we don't need to make the provinces expand and contract. So we should implement this design but without the chevrons.
screen shot 2018-07-25 at 3 34 51 pm

### PR DESCRIPTION
**Pull request by maxneuvians**
Closes #712

### CODE REVIEW

**Comment by sastels** [comment]
get NaN for distances when I allow geolocation

**Comment by sastels** [comment]
:( now zoom is broken. Have you been drinking?

**Comment by maxneuvians** [comment]
Could not replicate zoom error, must be user error

**Review by smcmurtry — APPROVED** [review]
Nice work!

**Pull request merged**
