### PR TITLE
Package upgrade for Sprint Security

### PR DESCRIPTION
**Pull request by maxneuvians**

### CODE REVIEW

**Comment by sastels** [comment]
Getting deploy error on Heroku
```
> Failed to build
       { Error: (client) ./components/benefit_cards_b.js
       Module not found: Error: Can't resolve './favourite_button_b' in '/tmp/build_d73e57846fb1d335772444e485f7eb85/components'
       @ ./components/benefit_cards_b.js 32:0-51
       @ ./components/benefit_list.js
       @ ./components/favourites.js
       @ ./pages/favourites.js
-----> Build failed
```

**Comment by maxneuvians** [comment]
I will specify a node version

**Comment by maxneuvians** [comment]
Node Alpine is running 10.6, so that is what I am specifying

https://github.com/nodejs/docker-node/blob/master/10/alpine/Dockerfile

**Comment by maxneuvians** [comment]
Deployment is fixed, now I am getting the new axe errors.

**Comment by maxneuvians** [comment]
I just ran the HTML snippets through https://axe-core.org/playground/ and they don't flag an error. I suspect there is an issue between `axe-jest` and the newest `jest` and `react`. I kept the old version of jest for now.

**Review by sastels — APPROVED** [review]
YOLO `¯\_(ツ)_/¯`

**Pull request merged**
