### PR TITLE
Change remove favourite button on saved page

### LINKED ISSUE #1946: New design to remove benefits from the saved page
https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5c5c6ae81af3542ca977e042

Note: This is for the saved page ONLY, benefits directory is unchanged.

### PR DESCRIPTION
**Pull request by brdunfield**
Closes #1946

### CODE REVIEW

**Comment by brdunfield** [comment]
[Users see a clear Remove button from the saved list different from the "Add" button on the directory](https://trello.com/c/cxlq8MtN/171-users-see-a-clear-remove-button-from-the-saved-list-different-from-the-add-button-on-the-directory)

**Comment by smcmurtry** [comment]
The close button looks kind of oval, could we use this instead? https://material.io/tools/icons/?icon=cancel&style=baseline

**Comment by smcmurtry** [comment]
Looks like the icon placement goes wonky when there's a long benefit name on a narrow screen: 
screen shot 2019-03-05 at 10 12 20 am

If you use `display: flex;` for the positioning that might help. See the `CardDetails` component for an example. 

Also the focus outline should be yellow for consistency.

**Review by smcmurtry — APPROVED** [review]
Nice work Bethany 😄 🦑

**Pull request merged**
