### PR TITLE
Added security md

### LINKED ISSUE #745: Create SECURITY.md
Create a security document for our upgrade process

### PR DESCRIPTION
**Pull request by maxneuvians**
Closes #745

### CODE REVIEW

**Comment by maxneuvians** [comment]
https://github.com/cds-snc/vac-benefits-directory/blob/0ac02f842add1ede96a01adad61c8da0562e2020/SECURITY.md

**Comment by sastels** [comment]
maybe put the "Run yarn upgrade..." on its own line?

**Comment by sastels** [comment]
"Example app locally" -> "Examine app locally"

**Review by sastels — APPROVED** [review]
minor comments, 🦑

**Pull request merged**
