### PR TITLE
Lunr upgrades

### PR DESCRIPTION
**Pull request by maxneuvians**
Started as a fix for #690 and #691 but also fixed a bug with not ORing words together in search

### CODE REVIEW

**Comment by sastels** [comment]
If I put benefits on the main page all the drop down suggestions go away when I type the 's'

**Comment by sastels** [comment]
And nothing appears in the list on BB

**Comment by maxneuvians** [comment]
I lowercased and hopefully it works - should you not be on a flight @sastels?

**Review by sastels — APPROVED** [review]
LGTM 🦑 
(Flight delayed 30 min)

**Pull request merged**
