### PR TITLE
[Do not merge until we have example content] Implement "See More / Less" Button in benefit cards

### LINKED ISSUE #1505: Implement a see more / see less button and move child benefits
Also remove the existing expansion panel:

screen shot 2018-11-29 at 5 02 12 pm
screen shot 2018-11-29 at 5 02 05 pm

### PR DESCRIPTION
**Pull request by brdunfield**
Closes #1505

### CODE REVIEW

**Comment by smcmurtry** [comment]
Just flagging that the content  "Disability Award can provide access to 6 other benefits " is changing to "by receiving Disability Award, the service member may also receive". See my comment on #1523.

**Comment by brdunfield** [comment]
Added a commit to close #1523

**Comment by sastels** [comment]
double colon
image

**Comment by sastels** [comment]
also, should the green "Learn More" button have the name of the benefit in it, as in https://github.com/cds-snc/vac-benefits-directory/issues/1505 ?

**Review by sastels — APPROVED** [review]
Small quibble: in the design the green link button doesn't have the arrow anymore. Other than that, looks great! 🦑 🦑 

When there are no child benefits the "show more" section is a bit silly, in that it only has the green button button. I assume the plan is to eventually add more content / example to it?

**Comment by smcmurtry** [comment]
@sastels Yes that's why we're waiting to merge this until we have some content to put into the "examples of what this program can provide" section.

**Pull request merged**
