### PR TITLE
Material upgrade

### PR DESCRIPTION
**Pull request by maxneuvians**
Upgrading Material UI per #381. Lots of changes, just working on fixing tests.

### CODE REVIEW

**Comment by maxneuvians** [comment]
This one just needs a once over with the Heroku PR app just to make sure it all works.

**Comment by maxneuvians** [comment]
I am already seeing some `//` and some trailing `/` which can be cleaned up

**Comment by maxneuvians** [comment]
Because this is going to break every ones node_modules and mess with a lot of active PRs feel free to approve when it makes strategic sense.

**Comment by sastels** [comment]
Let's wait till after the user testing on Wednesday, then it's fine to go IMO

**Comment by smcmurtry** [comment]
Great work Max! Now I can copy/paste import statements directly from the internet and they will work 😁

**Review by smcmurtry — APPROVED** [review]

**Comment by sastels** [comment]
Oh, so you approve this before my bookmarking, eh? Getting back at me for handing you those merge conflicts earlier! 😛

**Comment by smcmurtry** [comment]
😆

**Pull request merged**
