### PR TITLE
Add links to benefits cards

### LINKED ISSUE #116: Add hyperlinks to benefit cards using URLs from the DB

### PR DESCRIPTION
**Pull request by sastels**
resolves #116

### CODE REVIEW

**Review by maxneuvians — APPROVED** [review]
🦑

**Comment by sastels** [comment]
Alright @maxneuvians you can give this another look if you'd like.

**Comment by sastels** [comment]
opps, the all benefit page doesn't have the links in it :( I'll fix...

**Comment by maxneuvians** [comment]
LGTM x2 🦑 🦑

**Pull request merged**
